### ISSUE TITLE
color_replacements and material_replacements

### ISSUE THREAD

**Issue by KasperFranz** [skillbert/rsmv#13]
Hi,

Thank you for the work on this,

Can the color_replacements be applied as part of viewing the model?

An example is Loc 63329, which is more brownish than gray (I am guessing because color_replacement is not applied)

**Comment by skillbert** [comment]
This is due to a relatively new material property, before 2023 color_replacement was only applied to old (v0) materials with grayscale textures. It seems like jagex have added a toggle to also make this apply for some v1 materials but i haven't found it yet. 

I haven't played RS in about a year now so it's not really high priority for me right now. I can take a look again if you can supply me with a list of model id's and reference images.

**Comment by KasperFranz** [comment]
Examples:

- 69846 https://runescape.wiki/w/File:Al_Kharid_lodestone_(inactive).png
-  63329 https://runescape.wiki/w/File:Bed_(Citharede_Abbey,_1).png

**Comment by skillbert** [comment]
This seems to simply be a case of different lighting/environment effects. The issue i was talking about is about newer models and results in different colors, not just shades.
